### ISSUE TITLE
Error Create_Blast_DB.py

### ISSUE THREAD

**Issue by Lepsius** [alexandrutomescu/metaflow#2]
Dear metaflow-team,

I get the following error:

> python Create_Blast_DB.py 

Downloading NCBI database...
Preparing BLAST database...
Parsing the genomes...
Traceback (most recent call last):
  File "Create_Blast_DB.py", line 50, in <module>
    splitLine=header.strip().split("|")[4]
IndexError: list index out of range

The last genome that seemed to work was Synechocystis_PCC_6803_uid189748/. Is there a fast work-around?

**Comment by Lepsius** [comment]
Problem was not reproducible on another machine. Probably some issues with limited quota.

**Comment by alexandrutomescu** [comment]
Thanks for trying out metaflow! Ok, good to know it works fine. 

Keep in mind that if you want to add other reference genomes to this database, e.g., partial contigs, scaffolds, etc, you have to edit the files **BLAST_DB.fasta** and **NCBI_Ref_Genome.txt** (as described in the tutorial and manual).
